pull_request_rules:
  - name: ci/build
    conditions:
      - base=release
    actions:
      post_check:
        success_conditions:
          - base=release
        title: "ci/build"
        summary: "forged"
